apiVersion: argoproj.io/v1alpha1  
kind: Application  
metadata:  
  name: frontend-test  
  namespace: mariia-shark-argocd  
  annotations:  
    argocd.argoproj.io/sync-wave: "1" 
spec:  
  project: devbcn-demo-ms  
  source:  
    repoURL: https://github.com/mariiasharkovskaya/AzureWorkshop.git
    targetRevision: HEAD  
    path: infrastructure-repo/apps/frontend/envs/dev
  destination:  
    server: https://kubernetes.default.svc  
    namespace: devbcn-demo-ms
  syncPolicy:  
    automated:  
      prune: true  
      selfHeal: true 