apiVersion: argoproj.io/v1alpha1  
kind: AppProject  
metadata:  
  name: common-resources  
  namespace: mariia-shark-argocd  
spec:  
  description: "Project for common deployments"  
  sourceRepos:  
    - "*" 
  destinations:  
    - namespace: "*" 
      server: "*"    
  clusterResourceWhitelist:  
    - group: "*"  
      kind: "*"  
  namespaceResourceWhitelist:  
    - group: "*"  
      kind: "*"  