apiVersion: argoproj.io/v1alpha1  
kind: AppProject  
metadata:  
  name: devbcn-demo-ms  
  namespace: mariia-shark-argocd  
spec:  
  description: "Project for devbcn deployments"  
  sourceRepos:  
    - "*" 
  destinations:  
    - namespace: mariia-shark-argocd 
      server: "*"   
  clusterResourceWhitelist:  
    - group: "*"  
      kind: "*"  
  namespaceResourceWhitelist:  
    - group: "*"  
      kind: "*"  